development:
  host: '127.0.0.1'
  port: 9042
  keyspace: marid_dev

test:
  host: '127.0.0.1'
  port: 9042
  keyspace: marid_test

production:
  hosts:
    - 'cass1.marid.biz'
    - 'cass2.marid.biz'
    - 'cass3.marid.biz'
  port: 9042
  keyspace: marid_production
  username: 'myappuser'
  password: 'password1'
